version: "3.8"

volumes:
  neo4j:

services:
  neo4j:
    container_name: neo4j
    image: docker.io/bitnami/neo4j:4
    environment:
      - NEO4J_PASSWORD='neo4j'
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - 'neo4j:/bitnami'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:7474/", "||", "exit 1"]
      interval: 5s
      timeout: 2s
      retries: 10
    platform: linux/amd64
